services:

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./database/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    networks:
      - mynetwork
    restart: always

  backend:
    build: ./backend/
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    depends_on:
      - database
    networks:
      - mynetwork
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
