services:

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./database/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    healthcheck:
      test: [ "CMD", "psql", "-h", "localhost", "-U", "postgres", "-p", "5432" ]
      interval: 10s
      timeout: 15s
      retries: 1000000
    networks:
      - mynetwork
    restart: always

  backend:
    build: ./backend/
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork
    restart: always

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - mynetwork
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
