FROM python:latest


WORKDIR /backend

COPY requirements.txt .
COPY migrate.sh .
RUN	pip3 install -r requirements.txt && chmod +x ./migrate.sh

COPY . /backend/


CMD [ "bash", "/backend/migrate.sh" ]

