# Generated by Django 5.1.3 on 2024-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
