# Generated by Django 5.1.3 on 2024-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inventoryitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
