# Generated by Django 5.1.3 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_inventoryitem_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
