# Generated by Django 5.1.3 on 2024-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inventoryitem_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='img_url',
            field=models.CharField(blank=True, default='https://www.contentviewspro.com/wp-content/uploads/2017/07/default_image.png', max_length=255),
        ),
    ]
